name: recipe_finder
description: "A new Flutter project."

# This line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  provider: ^6.1.1            # 🔹 For simple state management
  shared_preferences: ^2.2.2  # 🔹 For saving search history, dark mode toggle etc.
  animations: ^2.0.11         # 🔹 For smooth fade/slide transitions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets, uncomment below and include your image files:
  # assets:
  #   - assets/images/logo.png

  # To add custom fonts, use this format:
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
